events{

}
http{
    upstream backend{
        server gateway1:7000;
        server gateway2:7000;
    }
    server{
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend;
        }
    }
}