events{

}

http{

    upstream backend{
        server backend0:7000;
        server backend1:7000;
        server backend2:7000;
        server backend3:7000;
    }

    server
    {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend;

        }
    }
}